#!/usr/bin/env bash
# mise description="Generate code from protobuf files"

set -e

# Create the output directory
mkdir -p models

echo "Generating proto files..."

protoc \
  -I data-viz-models/proto \
  -I. \
  --go_out=models \
  --go_opt=paths=source_relative \
  --go-grpc_out=models \
  --go-grpc_opt=paths=source_relative \
  data-viz-models/proto/*.proto

echo "Done."