// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChartData struct {
	ChartID string        `json:"chartId"`
	Data    []*ChartPoint `json:"data"`
}

type ChartPoint struct {
	Timestamp string    `json:"timestamp"`
	Values    []float64 `json:"values"`
}

type Mutation struct {
}

type Query struct {
}

type Settings struct {
	NumPlotsPerChart int32 `json:"NumPlotsPerChart"`
	NumPoints        int32 `json:"NumPoints"`
}

type SettingsInput struct {
	NumPlotsPerChart *int32 `json:"NumPlotsPerChart,omitempty"`
	NumPoints        *int32 `json:"NumPoints,omitempty"`
}
