// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChartData struct {
	ChartID string        `json:"chartId"`
	Data    []*ChartPoint `json:"data"`
}

type ChartDataTimestamp struct {
	Timestamp int64        `json:"timestamp"`
	ChartData []*ChartData `json:"chartData"`
}

type ChartPoint struct {
	Timestamp string    `json:"timestamp"`
	Values    []float64 `json:"values"`
}

type Query struct {
}
