// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: charts.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChartPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimestampUnixSeconds int64     `protobuf:"varint,1,opt,name=timestamp_unix_seconds,json=timestampUnixSeconds,proto3" json:"timestamp_unix_seconds,omitempty"`
	Values               []float64 `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *ChartPoint) Reset() {
	*x = ChartPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_charts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChartPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartPoint) ProtoMessage() {}

func (x *ChartPoint) ProtoReflect() protoreflect.Message {
	mi := &file_charts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartPoint.ProtoReflect.Descriptor instead.
func (*ChartPoint) Descriptor() ([]byte, []int) {
	return file_charts_proto_rawDescGZIP(), []int{0}
}

func (x *ChartPoint) GetTimestampUnixSeconds() int64 {
	if x != nil {
		return x.TimestampUnixSeconds
	}
	return 0
}

func (x *ChartPoint) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type ChartData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChartId string        `protobuf:"bytes,1,opt,name=chartId,proto3" json:"chartId,omitempty"`
	Points  []*ChartPoint `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
}

func (x *ChartData) Reset() {
	*x = ChartData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_charts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChartData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartData) ProtoMessage() {}

func (x *ChartData) ProtoReflect() protoreflect.Message {
	mi := &file_charts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartData.ProtoReflect.Descriptor instead.
func (*ChartData) Descriptor() ([]byte, []int) {
	return file_charts_proto_rawDescGZIP(), []int{1}
}

func (x *ChartData) GetChartId() string {
	if x != nil {
		return x.ChartId
	}
	return ""
}

func (x *ChartData) GetPoints() []*ChartPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type ChartDataList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ChartData `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ChartDataList) Reset() {
	*x = ChartDataList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_charts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChartDataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartDataList) ProtoMessage() {}

func (x *ChartDataList) ProtoReflect() protoreflect.Message {
	mi := &file_charts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartDataList.ProtoReflect.Descriptor instead.
func (*ChartDataList) Descriptor() ([]byte, []int) {
	return file_charts_proto_rawDescGZIP(), []int{2}
}

func (x *ChartDataList) GetItems() []*ChartData {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_charts_proto protoreflect.FileDescriptor

var file_charts_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x68, 0x61, 0x72, 0x74, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x34, 0x0a, 0x16, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75,
	0x6e, 0x69, 0x78, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x14, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78,
	0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22,
	0x51, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x72, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x68, 0x61, 0x72, 0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x74, 0x73, 0x2e,
	0x43, 0x68, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x22, 0x38, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x74, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x72,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0x4d, 0x0a, 0x0c,
	0x43, 0x68, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x74, 0x73, 0x2e, 0x43, 0x68,
	0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x32, 0x5a, 0x30, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x74, 0x6f, 0x73, 0x74,
	0x69, 0x63, 0x6b, 0x61, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d,
	0x64, 0x61, 0x74, 0x61, 0x2d, 0x76, 0x69, 0x7a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_charts_proto_rawDescOnce sync.Once
	file_charts_proto_rawDescData = file_charts_proto_rawDesc
)

func file_charts_proto_rawDescGZIP() []byte {
	file_charts_proto_rawDescOnce.Do(func() {
		file_charts_proto_rawDescData = protoimpl.X.CompressGZIP(file_charts_proto_rawDescData)
	})
	return file_charts_proto_rawDescData
}

var file_charts_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_charts_proto_goTypes = []interface{}{
	(*ChartPoint)(nil),    // 0: charts.ChartPoint
	(*ChartData)(nil),     // 1: charts.ChartData
	(*ChartDataList)(nil), // 2: charts.ChartDataList
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_charts_proto_depIdxs = []int32{
	0, // 0: charts.ChartData.points:type_name -> charts.ChartPoint
	1, // 1: charts.ChartDataList.items:type_name -> charts.ChartData
	3, // 2: charts.ChartService.GetChartData:input_type -> google.protobuf.Empty
	2, // 3: charts.ChartService.GetChartData:output_type -> charts.ChartDataList
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_charts_proto_init() }
func file_charts_proto_init() {
	if File_charts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_charts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChartPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_charts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChartData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_charts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChartDataList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_charts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_charts_proto_goTypes,
		DependencyIndexes: file_charts_proto_depIdxs,
		MessageInfos:      file_charts_proto_msgTypes,
	}.Build()
	File_charts_proto = out.File
	file_charts_proto_rawDesc = nil
	file_charts_proto_goTypes = nil
	file_charts_proto_depIdxs = nil
}
